'use strict';
// Business configuration. Keep the published CSV public; never put credentials here.
const CONFIG = {
 sheetURL: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRX3ME8gLubgdcM-QzUKRJ7GO0pabllVpknR11UGFBlOQ5YbCfmNf4rEAdOKTYIgdfi7i5an1Nx-L3K/pub?output=csv',
 whatsapp: '94719692801', facebookURL: '', fallbackDeliveryFee:350
};
const main=document.querySelector('main');
let products=[],loadState='loading',language='en',activeProduct=null,selectedColor='',selectedPattern='';
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=v=>{try{const u=new URL(String(v).trim());return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}};
const money=v=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:0}).format(v);
const list=v=>String(v||'').split(/[;,|\n]+/).map(x=>x.trim()).filter(Boolean);
// RFC-style CSV parsing: quoted commas/newlines, escaped quotes, CRLF and BOM.
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\r'||c==='\n')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Invalid CSV');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)return [];const headers=rows.shift().map(h=>h.replace(/^\uFEFF/,'').trim().toLowerCase().replace(/[\s_-]/g,''));if(!headers.includes('name')||!headers.includes('price'))throw Error('CSV needs Name and Price columns');return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])));}
function amount(v,fallback=null){const n=Number(String(v).replace(/(?:LKR|Rs\.?|,|\s)/gi,''));return String(v).trim()&&Number.isFinite(n)&&n>=0?n:fallback;}
function normalize(rows){const ids=new Set();return rows.filter(r=>r.name.trim()).map((r,index)=>{let id=(r.id||'').trim()||`bag-${index+1}`;if(ids.has(id))throw Error('Duplicate product ID');ids.add(id);const patterns={Blue:list(r.bluepatterns).map(safeURL).filter(Boolean),Pink:list(r.pinkpatterns).map(safeURL).filter(Boolean)};const colors=list(r.coloroptions||r.colors);for(const c of Object.keys(patterns))if(patterns[c].length&&!colors.some(x=>x.toLowerCase()===c.toLowerCase()))colors.push(c);return {id,name:r.name.trim(),price:amount(r.price),delivery:amount(r.deliveryfee,CONFIG.fallbackDeliveryFee),images:[r.imagelink||r.image,r.imagelink2,r.imagelink3].map(safeURL).filter(Boolean),out:/^(out\s*of\s*stock|sold\s*out|unavailable|0)$/i.test((r.status||'').trim()),colors,patterns,size:(r.size||r.sizes||'').trim(),descriptions:{en:r.descriptionen||r.description,si:r.descriptionsi,ta:r.descriptionta}};});}
const routeLink=p=>`#/product/${encodeURIComponent(p.id)}`;
const stock=p=>`<span class="badge ${p.out?'out':''}">${p.out?'Out of Stock':'In Stock'}</span>`;
const image=(url,alt)=>url?`<img src="${escapeHTML(url)}" alt="${escapeHTML(alt)}" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:'<span class="empty-image">Photo coming soon</span>';
const card=p=>`<a class="card" href="${routeLink(p)}"><div class="photo">${image(p.images[0],p.name)}${stock(p)}</div><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.size||'Made for everyday moments')}<span class="price">${p.price===null?'Price on request':money(p.price)}</span></p></a>`;
function catalog(){if(loadState==='loading')return '<p class="notice" role="status">Loading our bags…</p>';if(loadState==='error')return '<div class="notice" role="alert">We couldn’t load the collection. Please try again.<p><button class="btn" id="retry">Retry</button></p></div>';return '<div id="grid" class="grid"></div><p id="empty" class="notice" hidden>No bags match your search.</p>';}
const art=`<svg class="bag-drawing" viewBox="0 0 400 360" role="img" aria-label="Illustration of a baby bag"><ellipse cx="200" cy="320" rx="140" ry="16" fill="#987961" opacity=".18"/><path d="M104 141Q66 80 106 52Q147 25 167 119M296 141Q334 80 294 52Q253 25 233 119" fill="none" stroke="#385648" stroke-width="15"/><rect x="67" y="118" width="266" height="191" rx="38" fill="#5b7767"/><path d="M68 164H331" stroke="#dcd9b5" stroke-width="4"/><rect x="104" y="194" width="192" height="91" rx="15" fill="#7b9280"/><path d="M114 207H286M200 209V280" stroke="#c2cdb5" stroke-width="3"/><rect x="174" y="137" width="52" height="17" rx="4" fill="#e8dec3"/><path d="M51 201H78V275H56Q44 254 51 201M349 201H322V275H344Q356 254 349 201" fill="#476655"/></svg>`;
function render(){let hash=location.hash||'#/home';const detailMatch=hash.match(/^#\/product\/([^/]+)$/);let page=hash.slice(2);if(!['home','products','about'].includes(page)&&!detailMatch)page='missing';document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===`#/${detailMatch?'products':page}`;if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});activeProduct=null;selectedColor='';selectedPattern='';if(detailMatch){let id;try{id=decodeURIComponent(detailMatch[1]);}catch{id='';}const p=products.find(p=>p.id===id);if(loadState!=='ready'){main.innerHTML=`<a class="back" href="#/products">← Back to products</a>${catalog()}`;}else if(p){renderDetail(p);}else missing();}else if(page==='home'){main.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">For your beautiful new chapter</p><h1>Ranowin Production</h1><p>Little essentials. Big adventures. Thoughtfully made baby bags to keep everything close, from your first hospital visit to everyday outings.</p><a class="btn" href="#/products">Explore our bags →</a></div><div class="hero-art">${art}</div></section><div class="benefits"><div><strong>Room for every little thing</strong><p>Find the right bag and size for your family.</p></div><div><strong>A colour that feels like you</strong><p>Choose plain colours or available fabric patterns.</p></div><div><strong>Delivered to your doorstep</strong><p>Order personally with us on WhatsApp.</p></div></div><div class="section-top"><h2>The baby bag collection</h2><a href="#/products">View all →</a></div>${catalog()}`;if(loadState==='ready')showGrid(products.slice(0,3));}else if(page==='products'){main.innerHTML=`<p class="eyebrow">Made for little beginnings</p><h1>Our baby bags</h1><p>Choose your favourite. Make it yours.</p><div class="toolbar"><input id="search" type="search" aria-label="Search bags" placeholder="Search bags…"><select id="stockFilter" aria-label="Filter stock"><option value="all">All bags</option><option value="in">In stock</option><option value="out">Custom orders</option></select></div>${catalog()}`;if(loadState==='ready')showGrid(products);}else if(page==='about'){main.innerHTML=`<section class="about"><p class="eyebrow">Our story</p><h1>A little care, in every bag.</h1><p>Ranowin Production creates baby bags for parents and their little ones. We focus on practical storage, comfortable carrying, and colours and fabrics you’ll love.</p><p>Based in Pannipitiya, Sri Lanka. Browse our collection or speak with us to arrange a custom bag.</p><a class="btn" href="https://wa.me/${CONFIG.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp: +94 71 969 2801</a>${safeURL(CONFIG.facebookURL)?`<a class="btn secondary" href="${escapeHTML(safeURL(CONFIG.facebookURL))}" target="_blank" rel="noopener noreferrer">Visit our Facebook page</a>`:''}</section>`;}else missing();document.title='Ranowin Production';}
function missing(){main.innerHTML='<h1>Page not found</h1><p>This bag or page is no longer available.</p><a class="btn" href="#/products">Browse products</a>';}
function showGrid(items){const grid=document.getElementById('grid');if(!grid)return;grid.innerHTML=items.map(card).join('');document.getElementById('empty').hidden=items.length>0;}
const customCopy=`<aside class="custom"><strong>Made especially for you · Custom orders</strong><p lang="en">This bag is out of stock. Your custom bag will be stitched and delivered to your doorstep within 7 days. Message us on WhatsApp to select current fabric designs.</p><p lang="si">මෙම බෑගය දැනට තොගයේ නැත. ඔබගේ විශේෂ ඇණවුම මසා දින 7ක් ඇතුළත නිවසටම බෙදා හරිනු ලැබේ. දැනට තිබෙන රෙදි මෝස්තර තෝරා ගැනීමට WhatsApp හරහා අපට පණිවිඩයක් එවන්න.</p><p lang="ta">இந்தப் பை தற்போது கையிருப்பில் இல்லை. உங்கள் தனிப்பயன் பை தைக்கப்பட்டு 7 நாட்களுக்குள் உங்கள் வீட்டு வாசலுக்கு வழங்கப்படும். தற்போதுள்ள துணி வடிவங்களைத் தேர்ந்தெடுக்க WhatsApp மூலம் எங்களுக்குச் செய்தி அனுப்புங்கள்.</p></aside>`;
function renderDetail(p){activeProduct=p;main.innerHTML=`<a class="back" href="#/products">← Back to products</a><section class="detail"><div><div class="photo" id="mainPhoto">${image(p.images[0],p.name)}</div><div class="thumbs">${p.images.map((url,i)=>`<button type="button" data-photo="${i}" aria-label="View photo ${i+1}" aria-pressed="${i===0}">${image(url,`${p.name}, photo ${i+1}`)}</button>`).join('')}</div></div><div>${stock(p)}<h1>${escapeHTML(p.name)}</h1><p>${p.price===null?'Price confirmed on WhatsApp':money(p.price)}</p><label>Description language<select id="descriptionLanguage"><option value="en">English</option><option value="si">සිංහල</option><option value="ta">தமிழ்</option></select></label><p class="description" id="description"></p>${p.out?customCopy:''}${p.colors.length?`<fieldset><legend>Choose your colour</legend><div class="choices">${p.colors.map((c,i)=>`<button type="button" data-color="${i}" aria-pressed="false">${escapeHTML(c)}</button>`).join('')}</div></fieldset>`:''}<div id="patterns"></div>${p.size?`<p><strong>Size:</strong> ${escapeHTML(p.size)}</p>`:''}<div class="totals"><div><span>Bag</span><span>${p.price===null?'To confirm':money(p.price)}</span></div><div><span>Delivery</span><span>${money(p.delivery)}</span></div><div><strong>Total</strong><strong>${p.price===null?'To confirm':money(p.price+p.delivery)}</strong></div></div><form id="orderForm"><h3>Delivery details</h3><label>Full name<input name="customer" required autocomplete="name" maxlength="100"></label><label>Delivery address<textarea name="address" required autocomplete="street-address" rows="3" maxlength="600"></textarea></label><div class="row"><label>City<input name="city" required autocomplete="address-level2" maxlength="100"></label><label>Phone number<input name="phone" type="tel" required autocomplete="tel" inputmode="tel" maxlength="20" pattern="[+0-9() -]{9,20}"></label></div><label>Special note (optional)<textarea name="note" maxlength="600" rows="2"></textarea></label><p id="orderError" class="error" role="alert"></p><button class="btn" type="submit">${p.out?'Request Custom Order':'Order via WhatsApp'} ↗</button><p class="count">Your details open in WhatsApp. Send the message to confirm availability and arrange your order.</p></form></div></section>`;document.getElementById('descriptionLanguage').value=language;updateDescription();}
function updateDescription(){const el=document.getElementById('description');if(!el)return;el.lang=activeProduct.descriptions[language]?language:'en';el.textContent=activeProduct.descriptions[language]||activeProduct.descriptions.en||'Message us for details about this bag.';}
function currentPatterns(){return activeProduct?.patterns[Object.keys(activeProduct.patterns).find(k=>k.toLowerCase()===selectedColor.toLowerCase())]||[];}
function selectColor(i){selectedColor=activeProduct.colors[i];selectedPattern='';document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.color)===i));const patterns=currentPatterns();document.getElementById('patterns').innerHTML=patterns.length?`<fieldset><legend>Choose a ${escapeHTML(selectedColor)} fabric pattern</legend><div class="thumbs">${patterns.map((url,i)=>`<button type="button" data-pattern="${i}" aria-label="Select ${escapeHTML(selectedColor)} pattern ${i+1}" aria-pressed="false">${image(url,`${selectedColor} pattern ${i+1}`)}</button>`).join('')}</div><p class="count" id="patternLabel">Select a pattern to continue.</p></fieldset>`:'';document.getElementById('mainPhoto').innerHTML=image(activeProduct.images[0],activeProduct.name);}
function order(event){event.preventDefault();const p=activeProduct,form=event.target,error=document.getElementById('orderError');error.textContent='';if(!form.reportValidity())return;if(p.colors.length&&!selectedColor){error.textContent='Please choose a colour.';return;}if(currentPatterns().length&&!selectedPattern){error.textContent='Please choose a fabric pattern.';return;}const d=Object.fromEntries(new FormData(form));for(const key of ['customer','address','city','phone'])if(!d[key].trim()){error.textContent='Please complete your delivery details.';return;}if(!/^\+?\d{9,15}$/.test(d.phone.replace(/[() -]/g,''))){error.textContent='Please enter a valid phone number.';return;}const message=[`Hello Ranowin Production!`,p.out?'I would like to request a custom order.':'I would like to order this bag.',`Bag: ${p.name}`,`Product ID: ${p.id}`,`Colour: ${selectedColor||'Standard'}`,`Size: ${p.size||'Standard'}`,`Pattern: ${selectedPattern?`${selectedColor} pattern ${currentPatterns().indexOf(selectedPattern)+1}`:p.out?'Please share current fabric designs':'Plain / standard'}`,selectedPattern?`Pattern image: ${selectedPattern}`:'',`Bag price: ${p.price===null?'Please confirm':money(p.price)}`,`Delivery fee: ${money(p.delivery)}`,`Total: ${p.price===null?'Please confirm':money(p.price+p.delivery)}`,'',`Name: ${d.customer.trim()}`,`Address: ${d.address.trim()}`,`City: ${d.city.trim()}`,`Phone: ${d.phone.trim()}`,d.note.trim()?`Note: ${d.note.trim()}`:'',p.out?'Custom order: stitched and delivered within 7 days. Please confirm current fabric availability.':'Please confirm availability and delivery.',`Product: ${location.href}`].filter(Boolean).join('\n');location.assign(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(message)}`);}
async function loadProducts(){loadState='loading';render();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(CONFIG.sheetURL,{signal:controller.signal,cache:'no-store',credentials:'omit'});if(!response.ok)throw Error('Fetch failed');const text=await response.text();if(/^\s*</.test(text))throw Error('Not CSV');products=normalize(parseCSV(text));loadState='ready';}catch{loadState='error';}finally{clearTimeout(timer);render();}}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.id==='retry')loadProducts();if(b.dataset.color!==undefined)selectColor(Number(b.dataset.color));if(b.dataset.pattern!==undefined){selectedPattern=currentPatterns()[Number(b.dataset.pattern)];document.querySelectorAll('[data-pattern]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.getElementById('mainPhoto').innerHTML=image(selectedPattern,`${activeProduct.name}, ${selectedColor} pattern`);document.getElementById('patternLabel').textContent=`Selected: ${selectedColor} pattern ${Number(b.dataset.pattern)+1}`;}if(b.dataset.photo!==undefined){document.getElementById('mainPhoto').innerHTML=image(activeProduct.images[Number(b.dataset.photo)],activeProduct.name);document.querySelectorAll('[data-photo]').forEach(x=>x.setAttribute('aria-pressed',x===b));}});
document.addEventListener('change',event=>{if(event.target.id==='descriptionLanguage'){language=event.target.value;updateDescription();}if(event.target.id==='stockFilter')filterProducts();});
document.addEventListener('input',event=>{if(event.target.id==='search')filterProducts();});
document.addEventListener('submit',event=>{if(event.target.id==='orderForm')order(event);});
document.addEventListener('error',event=>{if(event.target.tagName==='IMG'){const placeholder=document.createElement('span');placeholder.className='empty-image';placeholder.textContent='Photo unavailable';event.target.replaceWith(placeholder);}},true);
function filterProducts(){const query=document.getElementById('search').value.toLowerCase().trim(),filter=document.getElementById('stockFilter').value;showGrid(products.filter(p=>p.name.toLowerCase().includes(query)&&(filter==='all'||(filter==='out'?p.out:!p.out))));}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);main.focus({preventScroll:true});});
// Seed the initial hash without adding history: product clicks add their own entries.
if(!location.hash)history.replaceState(null,'',`${location.pathname}${location.search}#/home`);
document.getElementById('year').textContent=new Date().getFullYear();
loadProducts();
